# QuickGameOS default MangoHud overlay.
# Toggle in-game with Shift_R+F12. Tweak visually with `goverlay`.

legacy_layout=false
gpu_stats
gpu_temp
gpu_core_clock
gpu_power
cpu_stats
cpu_temp
ram
vram
fps
frametime=1
frame_timing=1
gpu_name
engine_version
vulkan_driver
resolution

# Appearance
position=top-left
font_size=20
background_alpha=0.4
round_corners=8
text_color=D8DEE9
gpu_color=A3BE8C
cpu_color=81A1C1
fps_color_change
fps_value=30,60
fps_color=BF616A,EBCB8B,A3BE8C

toggle_hud=Shift_R+F12
toggle_logging=Shift_L+F2
